### ISSUE TITLE
Proofreader/Writer

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#102]
My English is bad and I have difficult to write correct text for singularity. I need one writer to help me to write text for description. You can also just proofreading my texts. Singularity is not a game with a lot of texts so it's not a long work. Few hours by weeks should be sufficient. It's would better if you are a native English speaker, but every help are welcome.

Otherwise, content will be slowly, very slowly, pushed to the master.

**Comment by nthykier** [comment]
Not an native English speaker, but I do not mind helping on an ad-hoc basis.

The parts you need help with, is that the missing text for the `testing/balancing` branch and other feature branches ? Or is it already in the `master` branch?

**Comment by Xenega** [comment]
For now, yes. But I have a new tech tree with a lot of new item and base to add to the game.

For example : 
* Heat signature, the tech for HeatSink
* Quantum Steath, Singularity play with metamaterial.

**Comment by e-o** [comment]
I can assist with proofreading.

**Comment by nthykier** [comment]
@Xenega 

Could you elaborate a bit about how you imagined this work flow would look like?  I have some suggestions for your `testing/balancing` branch; I would I go about submitting them to you and have them integrated?

**Comment by Xenega** [comment]
@Xenega
For the moment, I don't have a workflow. If you want add suggestions to testing/balancing, I think you can pull testing/balancing in your fork and create a new pull request.

**Comment by Xenega** [comment]
For @nthykier and not @Xenega
No, I am not mad.

**Comment by nthykier** [comment]
ok, I have opened #107 to add some English texts to the `testing/balancing` branch. :)

**Comment by Xenega** [comment]
I added a new label for pull request or issue where I need help to write text.
=> need writer

**Comment by sunfall** [comment]
I'm also happy to help with the new text in the game (as the author of most of the game's text in the first place).

**Comment by Xenega** [comment]
That's very cool. Very happy to welcome you again.

**Comment by sunfall** [comment]
Is this still an issue?  My current plan is to do a text-quality pass on any strings folks let me know about, and I'll keep a regular eye on the log for data/.

**Comment by nthykier** [comment]
I think we can close this now :)
