### ISSUE TITLE
Research CPU is not reset when you run out of bases that can research the tech of that danger level

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#103]
I experienced this in the `testing/balancing` branch and have now reproduced it on master.

If you build a base (e.g. the `Lunar Facility`) and have to research a tech of matching danger level (e.g. `Fusion Reactor`) and you lose that your base, you will still have some CPU capacity allocated to that research.  This is fine if you actually have another base that can take over that research, but in the concrete case, I only had bases left on earth.  If the game starts again, the remaining research time decrements as usual and allows me to cheat.

Note that the player is not able to allocate more CPU to the research (only less), so the cheat is a bit limited.

**Comment by Xenega** [comment]
Good catch !!! Thanks.
