### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#108]
I am developing the option screen, so I can add more option now. If you have idea...

**Comment by PeterJust** [comment]
Customizable hotkeys maybe? Might be a lot of work for a minor feature, though.

**Comment by nthykier** [comment]
@PeterJust Thanks for the suggestion. :)  I have opened a separate issue for this (#205).

I will close this bug as @Xenega has updated the Options screen for 1.0 (as far as I can tell)
