### ISSUE TITLE
Hard coded colours disagree with custom theme

### ISSUE THREAD

**Issue by cryptarch** [singularity/singularity#118]
Hi,

I tried creating a custom theme, and discovered that some GUI elements have hard-coded colours, which clash with the goals of the theme.

The goal is to create a "night mode" theme suitable for darkened rooms late at night. The two themes that come with Singularity by default are very bright and blue. This can be uncomfortable to look at in the dark.

The theme I am trying to make is very black-and-red based, here is a screenshot to show the intent:

![Main menu](https://user-images.githubusercontent.com/1596765/50360585-a6ab3100-05b4-11e9-8829-124115f41077.png)

Currently, the sliders and dialog background are hard-coded, as show in the following screenshots:

![Options screen](https://user-images.githubusercontent.com/1596765/50360791-56809e80-05b5-11e9-8f64-0829ade24012.png)

![Introduction](https://user-images.githubusercontent.com/1596765/50360814-76b05d80-05b5-11e9-945e-46deb4ef0b37.png)

![Australia base dialog](https://user-images.githubusercontent.com/1596765/50360859-9a73a380-05b5-11e9-9188-2395362f3f20.png)

I think there are only four lines where the blue hard-coding takes place:

```
$ grep -rnI blue code
code/graphics/slider.py:49:        background_color = background_color or "dark_blue"
code/graphics/slider.py:50:        slider_color = slider_color or "light_blue"
code/graphics/dialog.py:441:        kwargs.setdefault("background_color", "dark_blue")
code/graphics/dialog.py:682:                                  background_color="dark_blue",
```

**Comment by cryptarch** [comment]
(This issue is a follow up of https://github.com/singularity/singularity/pull/117 in which @Xenega encouraged me to identify hard-coded colours so that they don't interfere with any themes.)

**Comment by cryptarch** [comment]
I just found two more places where the colour is hard coded, in `code/screens/options.py`.

First on line 47:

```
        self.background_color = (0,0,50)
```

Secondly on line 228:

```
                              background_color=(0,0,50,255))
```

**Comment by Xenega** [comment]
Thanks.
If you want more flexibility for your theme, don't hesitate to ask. And don't hesitate to post your theme, a new theme would be cool.

**Comment by cryptarch** [comment]
Hi @Xenega 

Thanks, I do intend to share the theme, but it seems best to fix the problem with hard coded colours first. I am indeed asking you to make those hard coded colours more flexible :)

**Comment by rofl0r** [comment]
@cryptarch i think he already did. check the changes to the default theme in https://github.com/singularity/singularity/commit/49405a4c82fd0c2da9d2212ce52950d2ec4bf579
