### ISSUE TITLE
Unit test for savegame.

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#120]
I really need unit test for savegame.

**Comment by Quix0r** [comment]
Maybe my save-game can help to find backwards-compatibility issues? [Link](https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY?path=%2FSingularity-Endgame)

**Comment by Xenega** [comment]
Yes. Could you indicate the version (or better, git commit) the saves was done?

Sadly, backward compatibility is hard and I thought I could abandon it in the future, at least between major version. 

Could you test #123? The code is ugly for now and I am not very sure of what I should do.
