### ISSUE TITLE
Cannot save a game with the letter used as hotkey for "Ok" (i.e. "o" when language is English)

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#127]
Start a game, play a bit and then try to save it.  When prompted for a save game name, delete the original proposal and try typing a name containing the letter used as hotkey for "Ok".  For me, it always triggers the hotkey action rather than adding the letter to the save game name.

**Comment by Xenega** [comment]
Nice catch. 
It's a more generic bug. Every dialog with hotkey and field will bug. The GUI do not have concept of focus. 

We can add a hotkey for each field to get focus (and by default, no focus). The question is which key to use to remove focus. We can use ENTER, but we use it now as shortcut for yes.

**Comment by Xenega** [comment]
I think we need to add a list of focusable widget in each dialog and when a widget is focused, I can take all keys. You can switch focused widget with TAB. The first element of the list is the dialog which allows to perform hotkey. ENTER and ESC when a widget is focused switch the focus to the dialog.
