### ISSUE TITLE
Changing theme in-game does not fully change the theme

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#135]
I played with the theming feature and noticed that the theme system does not fully re-color all texts/widget on changing theme.

Notable examples:
 * Options -> General: The List menus do not change "list item border color" and "text selected color" on theme change.
 * Loading a game (after theme change) will still render the text of the "Suspicion" bar in the previous theme's color.  (Note the color is correct if singularity was starts up in the desired theme!)

(Redrew the comment about simple menu dialog; I cannot reproduce it with #134 + #137)

**Comment by nthykier** [comment]
Note: This *cannot* be tested with "Default" vs. "Vector" as they have the same color scheme.  I presume Nightmode (#119) would work.  Otherwise, I have a demo theme "Matrix" that triggers it (at https://github.com/nthykier/singularity/tree/theme-matrix)

**Comment by nthykier** [comment]
@cryptarch: I think I fixed that issue with #134.  Could you try that branch and reset the colors with `simple_menu_background` and `simple_menu_border`?

**Comment by cryptarch** [comment]
@nthykier Thanks, that did it. After your PR is approved, I'll add the new options to the nightmode theme.

**Comment by nthykier** [comment]
Closing as this issue was fixed by 5eaec7b. :)
