### ISSUE TITLE
Detection rate reducing techs/effects do not work

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#154]
Techs such as `Sociology` do not work at the moment. Related code:

From the Group class
```python
    @property
    def discover_bonus(self):
        return self.base_discover_bonus + max(self.changed_discover_bonus, 0)

# [...]

    def alter_discover_bonus(self, change):
        self.changed_discover_bonus += change
```

Observe that `max(self.changed_discover_bonus, 0)` will be `0` if `self.changed_discover_bonus` is negative.  Then follow up with the only call site of `alter_discover_bonus` which insists on passing a negative value:

```python
# [...]
            elif current == "discover":
                who = next(effect_iter)
                value = int(next(effect_iter))

                if who in g.pl.groups:
                    g.pl.groups[who].alter_discover_bonus(-value)
                else:
                    print "Unknown group/bonus '%s' in %s %s." \
                    % (who, self.parent_name, self.parent_id)
# [...]
```

And the techs.dat file always uses positive values.  This means that `changed_discover_bonus` will always be at *most* 0.  Quick testing on `very easy` seems to confirm this finding.

**Comment by Xenega** [comment]
Right. Misplaced defensive programming.
