### ISSUE TITLE
Grace period CPU

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#155]
First, the tweak of the CPU limits is too heavy. Really.

Second, there are a problem with this change. The grace period is now too different of the main part because we are not limited to create any number of base. In the main part, it's too dangerous to create a lot of base. We need a way to hint the player to not create a lot of base in grace period.

* First solution is to add a new hard rules about a limited number of base in Grace period. We need to warn the player when it create the last authorized base.
* We can add a limit of base as a new gameplay rule. However, it's not really a good gameplay rules because nobody will create a lot of base.
* Have you any other ideas ?

**Comment by nthykier** [comment]
As for "too many bases", I think that is easily solvable by making a warning.  The player can choose to ignore it or not and it would work at any part of the game (i.e. it would also trigger if they do it after the grace period). We can also add an upper limit on the number of bases allowed in the grace period (e.g. 8).  The warning could trigger with 6 bases as an example.

As for the CPU limit: What do you think should be the average number of CPU units allowed per day assuming people should have the full 22 day grace?  I presume the player would have to say below the `too many bases` warning for that.  So for the first many days, they would have at most 4x `Server Access` and 1x `Stolen Computer` (University computer) - or 5x `Server Access` if they give up their starting base (assuming we stick with 6 bases as triggering the `too many bases`-warning).

**Comment by nthykier** [comment]
An alternative variant of the CPU limit is to define what we allow/expect people to research while they have grace.

**Comment by sunfall** [comment]
You could pop up a warning dialog when either base count or CPU usage gets to, say, 80% of the grace limit as a "hey, you're about to cross the limit," with appropriate text.  Actually hard-limiting it seems unfun.

**Comment by nthykier** [comment]
I am considering this fixed by the current implementation of #196.
