### ISSUE TITLE
SDL_font too many file handle

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#156]
We have to create a SDL_font for each size we use. Each SDL_font have a file handle. With 3 font and 100 different sizes, we have a lot of handle for nothing. And in some OS we can exceed the limit of file handle.

Unfortunely, SDL_ttf do not provide solution that works and avoids our problem.

So, the solution have thought is to create a in memory file and make SDL Font link to it.

**Comment by nthykier** [comment]
A "quick-fix" could be to lazy load the fonts. At the moment, singularity will load 100 instances of all sizes (including size `0`) early at start up and that seems a bit wasteful given we are unlikely to ever use all of those sizes.

**Comment by nthykier** [comment]
@Xenega I have opened #159 which should solve the issue with file descriptors.  With both commits, I now see a steady 14 file descriptors open when I play singularity (previously it would use over 200).
