### ISSUE TITLE
feature request: buy multiple bases at once

### ISSUE THREAD

**Issue by rofl0r** [singularity/singularity#16]
since it's much more economic to buy servers instead of datacenters, i find myself buying 10-20 servers every few minutes of game time. my hand already hurts from pressing "n" for new base with the small finger of the left hand, then doing 2 quick clicks on "server access" with the mouse already positioned (right hand), and then return with the left hands thumb. (if buying more than 1 base, basenames could be assigned automatically)

**Comment by Quix0r** [comment]
Or this: click buy and choose how much you want to buy.

**Comment by rofl0r** [comment]
yeah, what i have in mind is that when you click on "new base" and then "server access" (or any other), a dialogue just like when you buy computers for a base opens where you enter the amount to buy. (the amount could default to how many you can currently afford).

**Comment by bmorel** [comment]
it would be probably useful, but not on impossible mode: buying a lot of servers would probably kill you ("only" is dangerous enough at start of game).
I think the best solution would be something like adding a text input with a default value of 1 (or to the last value) and a checkbox/button to enable name choice (with memory too), and those would take effect on clicking on create base.

**Comment by slemonide** [comment]
I think it would speed up the game play a lot if player would be able to create templates of bases and then instantiate them when needed.

**Comment by Quix0r** [comment]
Remember that for the main game's time (when you have to stay hidden), you DO NOT want multiple bases at one continent as this increases detection chance. So this feature is only nice at warm-up phase (the first 20 days) and after you win.

**Comment by Xenega** [comment]
Since I agree @Quix0r, this feature have very few usefulness now. So, if anyone want to make a pull request...

**Comment by nthykier** [comment]
Seems there is little interest in implementing the feature and it does not feel aligned with the game. I am closing it in favour of #146, which I think will be a better solution.
