### ISSUE TITLE
warehouse equipment lost if buying different CPU type

### ISSUE THREAD

**Issue by rofl0r** [singularity/singularity#17]
imagine a warehouse with 20 servers in it, then buying a single mainframe causes all 20 servers to be lost. this does hurt a lot when you have more expensive equipment in it.
imo it should be possible to have several CPU installed in peaceful co-existance.

**Comment by Quix0r** [comment]
Looks like a feature-wish to me and not a bug as this is currnently not possible/intended. Yes, currently you replace them all with the single main even when they could co-exist in a real-world warehouse. So you need to take that in consideration which to upgrade (have always at least one finished!) and which not.

**Comment by rofl0r** [comment]
well it's not clear if this is a feature or a bug, since the behaviour is not documented and at least for me, came as a surprise that threw me back a week of game-time.
imo, if you want to keep the current behaviour, there should at least be a confirmation dialog like "installing a mainframe will cause your 20 servers to be lost - are you sure you want that [Y/N]".

**Comment by Xenega** [comment]
The behavior will change with #35, but for 1.0 I will add a confirmation dialog.
