### ISSUE TITLE
Changing sleep/active state of a base does not immediately affect CPU availability

### ISSUE THREAD

**Issue by smiley1983** [singularity/singularity#179]
Changing the sleep/active state of a base does not take immediate effect.

Steps to reproduce:

 - Start a new game using latest development master branch (Very Easy difficulty for this example, but the bug seems independent of difficulty)
 - Send your CPU to sleep and note that you still have 1 CPU available for use
 - Build a base (Server Access) and set the clock running at full speed
 - When the new base is ready, the total CPU is updated correctly
 - Send your new base to sleep, you still have its CPU available
 - Research Intrusion with both bases asleep, set the clock running again
 - When research is complete, the total CPU available correctly drops to zero
 - Wake up both bases. You still have zero CPU available, even when the clock is running again.

I believe this is a recent regression - I won on impossible difficulty a couple of weeks ago with an up-to-date codebase, but I don't remember when exactly. If the bug had been there then, I would have noticed and I think winning might have been truly impossible. :)

**Comment by nthykier** [comment]
Fixed in #180.  Thanks again.
