### ISSUE TITLE
Build times are affected by game speed

### ISSUE THREAD

**Issue by dwentz89** [singularity/singularity#18]
Bases take less in-game time to build if you use slower game speed settings.

I've attached a save file which demonstrates the issue. It is building a datacenter with no modifiers to build speed, and with plenty of money to spend. Datacenters have a build time of 1 day, so this one should finish in exactly 24 hours.

[Example.zip](https://github.com/singularity/singularity/files/498822/Example.zip)

If you run on speed 4 till 20:00, then 3 till 23:56, then 2 till finish: Base finishes after exactly 24 hours as expected.
Speed 3 till 23:44, then 2 till finish: Base finishes at 23:45, which is 15 min early.
Speed 2 all the way: Base finishes at 22:37, 83 min early.

I didn't try speed 1 since that'd take forever to run, but since build times only make progress 1/min, It'd probably finish at the same time as speed 2.

I'd expect some small variations in build times from rounding differences and stuff, but saving 83 min on a 24 hour project is a 5.8% difference, which is pretty significant.

**Comment by MestreLion** [comment]
@dwentz89 , care to see if this issue was fixed?

**Comment by dwentz89** [comment]
Sorry, it's still happening exactly as I described.

Base construction uses `mins_passed`, not `secs_passed`, so that change shouldn't affect it at all.

**Comment by Xenega** [comment]
I found the origin of the problem. Tick are played completely. But some action can be finished before tick end time. In most game, it's not a problem because tick are very fast. But we have very long tick with the slower speed settings.  

Correct solution would allow tick to be partially played and abort with the time passed. But we need a major rework of the main game loop.

**Comment by dwentz89** [comment]
@Xenega That'd be a nice change too, but I don't see how it'd help this issue. The issue I found is that builds finish sooner than scheduled on low game speeds, but the issue you describe causes builds to finish later than scheduled on high speeds.

To use a variant of my example above, if you start a 24 hour build on day 5 at 00:30 and run at speed 2 until it finishes, it'd finish on day 5 at 23:07 because of my issue. If you instead run at speed 4, it'd finish on day 6 at 04:00 because of your issue. If both issues were fixed, it'd finish on day 6 at 00:30 regardless of game speed.

**Comment by Xenega** [comment]
Yes, you are right. My bad. There are a lot of different timing issues.

Every tick, the game calculate how much it could complete yours base. The result is the maximum
percentage of completion and is a float. Now to have the real amount, it needs to multiply it with total cost. The result is very close to a integer except you have float and float have rounding errors and floating point errors. It's sufficient to allow to spend one more minute in your base building every some tick.

The code use the ceiling function. With the rounding function, the error is gone. 

Replace
`cost_paid = numpy.maximum(numpy.cast[numpy.int64](numpy.ceil(raw_paid)),
                                  was_complete)`
by
`cost_paid = numpy.maximum(numpy.cast[numpy.int64](numpy.round(raw_paid)),
                                  was_complete)`

Another solution could be using the minimum between the amount spent and the amount that can be spent. But I think it's overkill. The only case when the percent is not close to a integer is when percent is capped. But in this case, by definition, it can't be superior to the capped number (in float representation).

**Comment by dwentz89** [comment]
That fixes it for me too, and I tested in speeds 2, 3, and 4. I think you should make a pull request for it.

Oh, and the reason the base finished at 23:48 for you is that you didn't switch to speed 2 at 23:44 like I did.
