### ISSUE TITLE
pygame 1.7 1.8 end of support

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#183]
We are thinking to remove the support of pygame 1.7 or 1.8.
Most distribution are using pygame 1.9 for few years and pip do not support anymore pygame less than 1.9.

Do anyone still use pygame 1.7 or 1.8 (and can test it) ?

**Comment by nthykier** [comment]
To be honest, I think we should cut support for versions that pygame upstream itself does not support as a general principle.

**Comment by Xenega** [comment]
Yes, I agree.

**Comment by rofl0r** [comment]
bumping to 1.9 should be OK. it has been around for many years, and doesn't add any unreasonable dependencies afaiu. so anyone that didn't already can simply update by using the newer tarball.

**Comment by Xenega** [comment]
Then so be it.
