### ISSUE TITLE
Unable to purchase components for bases

### ISSUE THREAD

**Issue by ardapekis** [singularity/singularity#192]
Bug is on master, reproducible in Ubuntu with Python 2 and Python 3.
To reproduce this bug:
1. Checkout the most recent commit on master: 6690cd6
2. Build a storage unit.
3. Try to purchase CPUs/reactors/security.
4. Observe that nothing happens.

The bug does not exist in commit 3149e80 and was introduced in commit 20aa225.

**Comment by nthykier** [comment]
Thanks, this has been fixed by #191
