### ISSUE TITLE
Consider the idea of rewriting the game in JavaScript?

### ISSUE THREAD

**Issue by quantuumsnot** [singularity/singularity#195]
We have workers, canvas/WebGL, in-browser database (IndexedDB, SQLite or plain json files), websockets ...

**Comment by Quix0r** [comment]
Maybe a clone is nice to see. But I guess entirely rewriting it is to much work that needs to be done.

**Comment by nthykier** [comment]
Given there is no visible support for a complete rewrite among the developers (including myself), I think I will close this suggestion.  As Quix0r mentioned, it is possible to make a clone in JavaScript if you are inclined.

An alternative that might be interesting is if there is way to transpile the game without (too much) loss of functionality. It could be useful as a way to enable people to demo the game without having to install it.  But then, it would still not be a rewrite.
