### ISSUE TITLE
GUI sounds are rather harsh

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#201]
In #178, @evilmrhenry noted the following change suggestion:

"""
GUI sounds are rather harsh. Recommend replacing with free sounds.
"""

Noted in this issue as a TODO to avoid forgetting about it.

**Comment by nthykier** [comment]
Suggestions for free and open source sounds are welcome. :)

**Comment by danuker** [comment]
I looked through the [first 5 pages of Freesound](https://freesound.org/search/?q=click&page=5#sound), when searching for "click".

Here are my favorites; I chose "softer" ones: 
1. Spacey wiggle: https://freesound.org/people/GameAudio/sounds/220178/
2. Hitting drumsticks together: https://freesound.org/people/florian_reinke/sounds/63531/
3. Tone inside: https://freesound.org/people/errysn/sounds/439523/
4. Soft typewriter: https://freesound.org/people/florian_reinke/sounds/63532/
5. Pen click: https://freesound.org/people/Adam_N/sounds/164642/
6. Slidey metal: https://freesound.org/people/kwahmah_02/sounds/256116/
7. Police radio (I can edit it and just keep the click when turning on): https://freesound.org/people/ERH/sounds/30328/

The ones I think are the best are spacey wiggle (1) and the police radio (7). What do you like?

**Comment by evilmrhenry** [comment]
I think any of these would be better than the existing sound. I also like 1 the best; my worry with 7 is that you're likely to leave some static behind after removing the unneeded bits, which might sound weird.

**Comment by danuker** [comment]
@evilmrhenry The static makes it sound a bit softer, I did leave a bit in on purpose. If you want to hear it before Freesound moderates it, here it is: http://www.fileconvoy.com/dfl.php?id=gbdc0d8095c6650041000215864c5fbda21bd567417

**Comment by danuker** [comment]
In case anyone is wondering, I used [Audacity](https://www.audacityteam.org/): I deleted everything I didn't want, then used short "Fade in" and "Fade out" effects on the ends of the file.

**Comment by evilmrhenry** [comment]
I think I still prefer 1. If you go with 7, be sure to remove the empty bit at the start, in order to give more immediate feedback.

**Comment by danuker** [comment]
@evilmrhenry I am fine with 1. I'll open a pull request, after investigating why there are 4 sounds in the clicks folder.

**Comment by nthykier** [comment]
> @evilmrhenry I am fine with 1. I'll open a pull request, after investigating why there are 4 sounds in the clicks folder.

Thanks for working on this. :)

The reason why there are 4 sounds file is because singularity have four different click sounds.  The game chooses one at random for each time you click.  Basically you replace `click1.wav` with the sound you want and delete the rest (if we end up with exactly one click sound).

**Comment by danuker** [comment]
When I replaced `click0.wav` or `click1.wav` with the new one, I get a crash right after the game window is created:

https://github.com/danuker/singularity

```
$ python3 singularity.py 
Singularity 1.0a1 (commit: singularity-1.0a1-39-gf352278)
Running under Python 3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20191022]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/dan/.local/share/singularity/log/error.log (lazily created when something is logged)
free(): double free detected in tcache 2
Aborted
```

**Comment by danuker** [comment]
The old file has this in its header:
`RIFF WAVEfmt`
But the new one has:
`RIFF ] WAVEbextZ`

It could be a modern format of WAV (**ext**ension?) not supported by PyGame. I will look into it some more.

**Comment by danuker** [comment]
Re-exported through Audacity and it works! (and has the `WAVEfmt` header).
