### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by PeterJust** [singularity/singularity#206]
Moin,
I wanted to have a go at all the new stuff. But there seems to be a problem in buyable.py.

Steps I took:
(0 configuring warnings -> no warning for cpu pool empty and not all avail cpu used)
1) Start game in normal mode
2) Build 5 bases (in South America)
3) Research Personal ID
4) Build Storage Unit
5) Trying to add security -> game crash

> Singularity version 1.0a1 (commit: singularity-1.0a1-22-g1c162ba)
> Python version 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
> Exception in function show at Mon Dec 16 14:51:34 2019 CEST:
> ```
> Traceback (most recent call last):
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/safety.py", line 59, in safe_call
>     return func(*args, **kwargs)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 230, in show
>     result = self.handle(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 376, in handle
>     return self.call_handlers(handlers, event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 391, in call_handlers
>     handler(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 155, in handle_event
>     self.activate_with_sound(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 168, in activate_with_sound
>     self.activated(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 196, in activated
>     self.function(*self.args, **self.kwargs)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/map.py", line 651, in open_location
>     dialog.call_dialog(self.location_dialog, self)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 123, in call_dialog
>     retval = dialog.show()
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/location.py", line 173, in show
>     return super(LocationScreen, self).show()
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 230, in show
>     result = self.handle(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 376, in handle
>     return self.call_handlers(handlers, event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 391, in call_handlers
>     handler(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 155, in handle_event
>     self.activate_with_sound(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 168, in activate_with_sound
>     self.activated(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 196, in activated
>     self.function(*self.args, **self.kwargs)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/location.py", line 234, in open_base
>     dialog.call_dialog(self.base_dialog, self)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 123, in call_dialog
>     retval = dialog.show()
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/base.py", line 382, in show
>     return super(BaseScreen, self).show()
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 230, in show
>     result = self.handle(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 376, in handle
>     return self.call_handlers(handlers, event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 391, in call_handlers
>     handler(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 155, in handle_event
>     self.activate_with_sound(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 168, in activate_with_sound
>     self.activated(event)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/button.py", line 196, in activated
>     self.function(*self.args, **self.kwargs)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/base.py", line 364, in build_item
>     result = dialog.call_dialog(build_dialog, self)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 123, in call_dialog
>     retval = dialog.show()
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/base.py", line 64, in show
>     self._update_desc_pane()
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/graphics/dialog.py", line 731, in _update_desc_pane
>     self.desc_func(self.description_pane, key)
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/screens/base.py", line 82, in on_change
>     g.pl.considered_buyables = [buyable.Buyable(self.item, count=1)]
>   File "/home/malibu/Dokumente/singularity/singularity/singularity/code/buyable.py", line 114, in __init__
>     self.name = spec.name
> AttributeError: 'NoneType' object has no attribute 'name'

**Comment by nthykier** [comment]
PeterJust:
> Moin,
> I wanted to have a go at all the new stuff. But there seems to be a problem in buyable.py.
> 
> Steps I took:
> (0 configuring warnings -> no warning for cpu pool empty and not all avail cpu used)
> 1) Start game in normal mode
> 2) Build 5 bases (in South America)
> 3) Research Personal ID
> 4) Build Storage Unit
> 5) Trying to add security -> game crash
> 
> 
>> Singularity version 1.0a1 (commit: singularity-1.0a1-22-g1c162ba)
>> Python version 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
>> Exception in function show at Mon Dec 16 14:51:34 2019 CEST:
>> ```
>> [...]
> 

Hi PeterJust,

Thanks for reporting the issue.

I believe it is now fixed in the master branch. :)

Thanks,
~Niels
