### ISSUE TITLE
Can't scroll lists with keyboard initially, without clicking them

### ISSUE THREAD

**Issue by danuker** [singularity/singularity#211]
**Describe the bug**
Can not move up or down any list after starting the game, without having clicked it before

**To Reproduce**
1. Run the game executable/script
2. DO NOT click on anything.
3. Press L to load a game
4. Try to scroll down using keyboard down arrow: **you can't**.
5. Click on the currently selected item (first savegame)
6. Now, keyboard up/down works **for that list and others** but **not all in the game**.

Also, if you load the first savegame (by pressing Enter without needing to scroll) later lists don't work with the keyboard either (choosing a base, or a warehouse feature inside it (PC / Gaming PC..., network...)).

If you click on a savegame, choosing a base in the continent still doesn't work, but choosing a warehouse feature does work).

Another variant:

1. Start a new game
2. DO NOT click on anything
3. Press R to get to the research list
4. Try to scroll down using keyboard down arrow: **you can't**.
5. Click on the currently selected research item (CPU Pool)
6. Now, keyboard up/down works.
7. Keyboard up/down still works after closing and re-opening the research list.

**Expected behavior**
Can use lists without using the mouse

**Desktop (please complete the following information):**
 - OS: `Linux debian 5.3.0-3-amd64`
 - Python version `Python 3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20191022]`
 - Version `Singularity 1.0a1 (commit: singularity-1.0a1-53-g6ce8ee2)`

**Additional context**
It is not a big inconvenience while playing, because once you have clicked every list in the game, they all work until you close the game and restart (can continue keyboard-only).

**Comment by danuker** [comment]
Thank you! Almost all of the lists work now, except for one: when creating a new base. Should I create a new ticket for this?

**Comment by nthykier** [comment]
Dan Haiduc:
> Thank you! Almost all of the lists work now, except for one: when creating a new base. Should I create a new ticket for this?
> 

Thanks for testing and confirming. :)

I have fixed the NewBaseDialog in
4e770864038738b8a4e0f3f3f422e29cc105a899.  If you spot any additional
issues, feel free to file an issue for it.  :)  It is more visible to
others and helps me find it again if I end up taking a break from
singularity development (i.e. less risk of your issue being overlooked).

**Comment by danuker** [comment]
It works! I can play with the keyboard. The Shift+Right Arrow works very nicely! Thanks a bunch!
