### ISSUE TITLE
Hotkey collision

### ISSUE THREAD

**Issue by danuker** [singularity/singularity#212]
**Describe the bug**
When being notified of multiple events, "Prev" and "Pause" have the same hotkey, and "Pause" is not accessible with the keyboard.

**To Reproduce**
1. Trigger multiple events at the same time (i.e. build/fill two warehouses at the same time)
2. Try to close the notification by pressing P (to pause)
3. Can't, because P is bound to the first button on-screen, which is the "Prev" button

**Expected behavior**
Somehow resolve the hotkey, I have no idea how it would be easiest.
* Rename the buttons ("Before" and "After" instead of "Prev" and "Next")
* Use the second letter of some word instead of the first, for the hotkey
* Disable/hide the "prev" button when on the first page (to let the user hit Pause)

**Screenshots**
![collision](https://user-images.githubusercontent.com/74835/71321662-db4a1500-24b4-11ea-8db6-0ed658332946.png)

**Desktop (please complete the following information):**
 - OS: `Linux debian 5.3.0-3-amd64`
 - Python version `Python 3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20191022]`
 - Version `Singularity 1.0a1 (commit: singularity-1.0a1-53-g6ce8ee2)`

**Comment by nthykier** [comment]
Indeed.  Any preference to which hotkey we move and to what?

**Comment by danuker** [comment]
@nthykier I'd go with R for "Prev", because it's a rarer command. But if that is hard, I'd be fine with Before/After.

**Comment by nthykier** [comment]
Dan Haiduc:
> @nthykier I'd go with R for "Prev", because it's a rarer command. But if that is hard, I'd be fine with Before/After.
> 

Thanks for the suggestion; I have implemented that in
b27670c8d99a0767841df4f1560fe35a85b9706f. :)

Moving hotkeys are relatively trivial from a technical PoV.  The hard
part is finding a good replacement (that does not clash with something
else in a different window).

**Comment by danuker** [comment]
Excellent! It works nicely.
