### ISSUE TITLE
Endgame: Singularity requires pygame.

### ISSUE THREAD

**Issue by Quix0r** [singularity/singularity#213]
The said message comes with latest `master` code. I have pygame3 (Python3) installed. Here is the full console output:
````
$ ./run_singularity.sh 
Singularity 1.0a1 (commit: singularity-1.0a1-66-g15bcf42)
Running under Python 3.7.2+ (default, Feb 27 2019, 15:41:59) [GCC 8.2.0]
Endgame: Singularity requires pygame.
$
````

**Comment by nthykier** [comment]
Roland Häder:
> The said message comes with latest `master` code. I have pygame3 (Python3) installed. Here is the full console output:
> ````$ ./run_singularity.sh 
> Singularity 1.0a1 (commit: singularity-1.0a1-66-g15bcf42)
> Running under Python 3.7.2+ (default, Feb 27 2019, 15:41:59) [GCC 8.2.0]
> Endgame: Singularity requires pygame.
> $
> ````
> 

Does it work if you use:

    python3 -m singularity

instead?

If so, then I think it might be because I forgot to preserve the orignal
PYTHONPATH variable in run_singularity.sh.

**Comment by nthykier** [comment]
Hi @Quix0r,

Can you check whether this is still an issue in master@7a931fd775fa5ee7f5d94e26c6d637608413b84f ?

**Comment by Anrock** [comment]
@nthykier just checked, same.

**Comment by nthykier** [comment]
@Anrock Thanks for the retest. :)

The results were sadly not what I had hoped.

I have pushed commits 2833916e02b69c325a42e911b5fe0318dc7911b1 and 2ca2cc7f6dc3598927acc0dfcc0df9a514fcefa6, which will enable us to get the real stacktrace with `--debug`.  Could you please do a git pull and then run:

```
python3 -m singularity --debug
```

And paste the resulting output in this ticket?  It should include a directory listing of where of where your python program will load modules from - if possible, please verify that pygame (for python3) is installed in one of those directories.

**Comment by Anrock** [comment]
@nthykier sorry, seems to be false alarm. I didn't actually had pygame and numpy installed (and even pip, wtf). After installing all that `./run_singularity.sh` worked just fine on latest master.

**Comment by nthykier** [comment]
@Anrock Glad to hear that it now works for you. :)

@Quix0r  Please let me know if this is still an issue for you.  If it is, please follow up with the debug information from https://github.com/singularity/singularity/issues/213#issuecomment-569340156 .

**Comment by Quix0r** [comment]
@nthykier I got this:
````
$ bash -x run_singularity.sh 
++ dirname run_singularity.sh
+ DIR=.
+ PYTHON=python3
+ PYPATH=.
+ PYTHONPATH=.
+ python3 -m singularity
Singularity 1.0a1 (commit: singularity-1.0a1-74-g5e574fe)
Running under Python 3.7.2+ (default, Feb 27 2019, 15:41:59) [GCC 8.2.0]
Endgame: Singularity requires pygame.
$
````

**Comment by Quix0r** [comment]
Guess what? `python3-pygame` and `python3-numpy` was not installed. False alarm! Maybe worth mentioning it that the package names are different?
