### ISSUE TITLE
Possibly untranslatable parts

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#216]
> Note the game is not at 100% translatability now, apparently, a couple of things (like the "Concepts" section of the knowledge thing) are untranslatable (or the PO files haven't been updated).

_Originally reported by @Wuzzy2 in #215_

**Comment by Wuzzy2** [comment]
To be more precise: Strings I have seen untranslatable:

- The entire "Conepts" section in the knowledge database
- The word "Bases:" in the top right corner of the world map screen

**Comment by nthykier** [comment]
@Wuzzy2: Thanks for the clarifications. :)

I have regenerated the POT file and the `BASES` label should now be translatable.

The `Concepts` part is a bit more tricky and is still impossible for now.
