### ISSUE TITLE
Bad usability in knowledge base

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#220]
**Describe the bug**
The mouse wheel asuage of up/down keys is buggy in the knowledge base.

If you use it in the left text list, it jumps all the way to the top or buttom.

If you use it in the right text list, only the right list will react.

If you push the up or down keys, only the left list will change. It's not possible to change the entry in the right list.

**To Reproduce**
1. Use the mouse wheel on the left or right text list and see what happens

**Expected behavior**
* When mousewheel used on left list: Scroll by one entry
* When mousewheel is used on right list: Scroll right list
* There's *some* way to change the right list entry with keys

**Desktop:**
 - OS: GNU/Linux
 - Python version: 3.8.1
 - Version: 00b8d20

**Comment by nthykier** [comment]
Indeed, the keyboard and mouse handling is suboptimal in the Knowledge menu.  Sadly, I cannot figure out how to fix it in a good way, so for now I am getting it `help wanted`.
