### ISSUE TITLE
Inconsistent and confusing use of decimal point vs decimal comma

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#226]
**Describe the bug**
Context: English uses the decimal point to denote values <1 and the comma as thausands separator.

But other languages have different conventions. In German, for example, it's the other way around.

The game correctly uses comma or point for most numbers in German. The mistake is when “million/billion/trillion/quadrillion” is used.

Example:

"80.00Mio. Geld" (80.00mi money)

In contrast, numbers like 300000 are rendered correctly as "300.000" in German.

The bug seems to only affect numbers with the “million” (etc.) modifier. The rest is fine, apparently.

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Python version: 3.8.1
 - Version: d26b45ac396fe8d2483f8dda8633f7477cb92762

**Comment by nthykier** [comment]
Hi,

Could you provide savegames or/and screenshots that demonstrate the issue?  My issue is that I cannot tell where you see the "300.000" being rendered correctly vs. where it is rendered wrong (e.g. the cash label in the top right corner always appear to be wrong as I understand your report)

**Comment by Wuzzy2** [comment]
The bug is that when the modifier “mi/bi/tr/qu" is used, the number renders incorrectly, and when the modifier is not used, it is rendered correctly. This is consistent everywhere, it does not matter where the number shows up.

Examples:

* "300.000 CPU" (OK)
* “20,00%” (OK, for 20%)
* "3.45Mio. Geld" (=money) (not OK, should be "3,45Mio. Geld")

Screenshots:
https://satoshiupload.com/images/q1ovZ9b8RX.png
https://satoshiupload.com/images/ITZwssiy9a.png

The numbers that are underlined yellow are incorrecly using the period but it should be the comma. All other numbers are displayed correctly.

**Comment by nthykier** [comment]
Thanks; I was missing the locale definition for de_DE so the thousand separator never appeared for me.
