### ISSUE TITLE
Research is unreadable in Nightmode

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#227]
**Describe the bug**
If you select the Nightmode theme, then research something to like over 50% (so that the progress bar is very long), the research name can't be read (red text on red background).

**To Reproduce**
1. Select "Nightmode" theme
2. Reseach something to over 50%
3. Open the research window and try to read the name of the project

You can't. The progress bar is red, as well as the text. ;-)

**Comment by nthykier** [comment]
Hi @cryptarch 

Would you be interested in looking at this issue and #225, which are both related to the Nightmode theme, you made for singularity a while back?

**Comment by nthykier** [comment]
@cryptarch I have committed a fix for this, but it could probably still use a review (I chose a dark gray to make it visible which does not quite fit the red, but it works).
