### ISSUE TITLE
Music won't play on Linux

### ISSUE THREAD

**Issue by ElonSatoshi** [singularity/singularity#229]
**Describe the bug**
Singularity 1.0b1 won't play music on Debian 10

**To Reproduce**
1. Download [Singularity v1.0b1](https://github.com/singularity/singularity/releases/download/v1.0b1/singularity-1.0b1.tar.gz) and [Music pack v7](http://emhsoft.com/singularity/endgame-singularity-music-007.zip) and install pygame and numpy with pip3 if necessary
2. Extract Singularity somewhere, create music/ directory, extract music in directory, move music files out of endgame-singularity-music-007 directory.

```
~/singularity-1.0b1
 % ls music 
 Aberrations.ogg           Awakening.ogg    Deprecation.ogg                        Inevitable.ogg      Nebula.ogg              win
'Advanced Simulacra.ogg'   By-Product.ogg   endgame-singularity-music-README.txt   lose               'Orbital Elevator.ogg'
'A New Journey.ogg'        Coherence.ogg   'Enemy Unknown.ogg'                    'Media Threat.ogg'  'Through Space.ogg'
```

3. Run `./run_singularity` in a terminal
4. Note the lack of music playing. I also occasionally get a `ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred` message in the terminal.

**Expected behavior**
Music should play. The README says soundtracks should be randomly played during gameplay.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster
 - Python version 3.7.3
 - Version 1.0b1

**Additional context**

**Comment by nthykier** [comment]
Hi,

I suspect that the music directory should be moved under `singularity` (in your case `~/singularity-1.0b1/singularity/music`) and we have simply forgotten to update the docs to match the new reality.

Can you confirm that the music works if you move it into the singularity subdir?

**Comment by ElonSatoshi** [comment]
Yes, I can confirm that. Thanks!

Where would I put the music directory within ~/.config/singularity/ ?

**Comment by nthykier** [comment]
If you want it in your user folder, then it should be one of:
`~/.local/share/singularity/singularity/music`
`~/.local/share/singularity/music`

(I think it is former, but it might the latter - I have not tested either yet)

**Comment by nthykier** [comment]
Turns it that my hunch was wrong and it was the latter. :)  Update to the README coming up
