### ISSUE TITLE
Advanced bases never finish construction

### ISSUE THREAD

**Issue by MartenKahr** [singularity/singularity#23]
Took the game up after many years for some nostalgia enjoyment, and discovered that late-game bases (starting with the Ocean base) never finish construction, making the game unwinnable. The issue seems to be with the consumption of CPU power. I can see on the finances screen that the sum of CPU power slated to construction is in the millions, and even as it goes down toward zero, it eventually loops back to over seven hundred million CPU, which seems to be the maximum with a Moon base and an Ocean base ongoing.  I also noted the same issue with building a Time Capsule: it took far more CPU to finish construction than I anticipated, despite having the money, but unlike the Undersea and Moon bases, it did eventually finish.

System Parameters:
OS: Windows 7 (64bit)
CPU: Intel i7-4790
RAM: 8GB
GPU: Radeon RX560
Endgame Singularity: v0.30c

**Comment by eisterman** [comment]
It's not a bug, the advanced bases have a cost even in CPU elaboration, maintain some CPU not assigned and the construction will advance.

I for not forget it assing every all the CPU not to "Money" because automatically if there isn't anything to consume the CPU power, automatically it goes to Money-making

**Comment by MartenKahr** [comment]
Ah, I see. Reading the instructions, I mistakenly understood that assigning CPU to CPU Pool would count toward construction, but it's only completely unassigned CPU that count for construction.
