### ISSUE TITLE
Changing translations midgame does not update translations for research names

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#232]
**Describe the bug**
Changing translations midgame does not update translations for research

**To Reproduce**
1. Start or load a game
2. Go to Menu, Options and change from (e.g.) English to German and return the map screen.
3. Select the Research/Task menu and notice how the research uses a mixture of German and English (The `Research` in `Research X` is translated but the tech name is not)
4. Go to the Knowledge screen and scroll through the Tech names, which are all still in English.

**Expected behavior**
The translation change should update immediately in the Research/Task menu and in Knowledge screen.

**Desktop (please complete the following information):**
All OS/Python versions

**Additional context**
This is almost certainly a regression from when we moved from data files to ".po" files for translation in-game data content.

**Comment by Wuzzy2** [comment]
You could just add a message to tell the player to restart the game.

**Comment by nthykier** [comment]
I think we used to have that a while back.  However, several contributors have put significant effort into making it "just work(tm)", so I intend to take a stab at fixing it first. :)
