### ISSUE TITLE
Custom resolution is broken

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#236]
The custom resolution input fields are broken.
If you enter a custom number or hit backspace, the text field does not properly update. Instead, the new characters just smear over the text field, quickly resulting in unreadable text.

Also, you can enter letters.

Finally, I never seem to get the custom resolution to work in the first place in window or fullscreen mode. It seems my input is just ignored The resulution/window size changes, but rarely to the size I have entered. (What I do: 1. Click “Custom” 2. Enter numbers 3. Click OK). 

Version: 6a81340cc29be0e5f010e0c0a12bb5245709a8a3
Tested on GNU/Linux, Phython 3.8.1

**Comment by Xenega** [comment]
You need to click to click on CUSTOM. It's a button.

**Comment by Wuzzy2** [comment]
> You need to click on CUSTOM. It's a button.

I did, but it didn't work.

> (What I do: 1. Click “Custom” 2. Enter numbers 3. Click OK).

But I figured out the order was wrong. I needed to swap steps 1 and 2.

**Comment by Xenega** [comment]
@Wuzzy2 Can you test #236 ?

**Comment by Wuzzy2** [comment]
????
#236 is THIS issue, lol.

**Comment by Xenega** [comment]
Sorry, #242

**Comment by Wuzzy2** [comment]
Works fine. :+1:
