### ISSUE TITLE
Confusing power state of empty bases or bases under constructions

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#239]
**Describe the bug**
The power state for bases that are empty or under construction or are building CPU is not displayed in the list and are displayed incorrectly if you open the base.

The way this game handles the base power state is a bit confusing and illogical.

**Analysis:**

Currently, bases only have 2 “official” power states: Active and Sleep. As far I understand, in Active, the base contributes CPU, but it is vulnerable to discovery. In Sleep, the base does not contribute any CPU, but the discovery% is reduced. But Active and Sleep don't actually describe all possible states a base can be in. Here's the list of all “true” states I am aware off:

1. Processors are Active: Contributes CPU, vulnerable to discovery
2. Processors are in Sleep: No CPU contribution, reduced discovery%
3. Empty base: Can be secretly active or sleeping (#238), but I'm certain this is unintended
4. Processors under construction: No CPU contribution, vulnerable to discovery
5. Base under construction: No CPU contribution, vulnerable to discovery (I think)

In cases 3-5, the column that normally says “Active” or “Sleep” is empty.

In case 3, if you open the base, it says “Active” or “Sleep” (you can actually toggle it, but I don't think it actually means anything). Neither state makes sense.
In case 4, if you open the base, it always says “Active”. Which is misleading.
In case 5, you can't open the base. So at least this case is correct.

The behavior of cases 3 and 4 doesn't make sense.

## Suggestion:

Add the special power state “Offline”. This power state is used for cases 3-5. This special state is only displayed when the base is empty, is under construction or processors are currently being built. The power state should also not be changable while in the Offline state.

Also, the power state should not be toggable at all for empty bases (see #238).

Now, bases have a clear power state:

* Active: Contributes CPU, discoverable
* Sleep: No CPU contribution, reduced discovery%
* Offline: No CPU contribution, discoverable

It's unclear how empty bases are meant to behave, however. Currently, they can be Active or Sleep (#238), but really they should only be in one state which can't be toggled by the player.
The question is how discoverable empty bases should be. Full discovery% or reduced? Or even zero?

**Comment by Xenega** [comment]
@Wuzzy2 Very good idea. I implemented it in pr #245.

**Comment by Wuzzy2** [comment]
I will test it when it's merged.

**Comment by Xenega** [comment]
@Wuzzy2 could you test before ? it's better not introduce bug in master

**Comment by Wuzzy2** [comment]
No, I can't.
