### ISSUE TITLE
Incorrect CPU displayed in continent with CPU bonus/malus

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#241]
If you try to build CPU in a base in a continent with CPU bonus/malus, the added CPU is not displayed correctly.

How to reproduce:
1. Build a storage unit in a continent with CPU bonus
2. Open base
3. Open the “build CPU” window
4. Select Server, set count to 1
5. Look what is says in the 3rd line (“Generates X CPU”)
6. Look what it says in the bottom-most line (“CPU per day: Y”)

Expected: X equals Y.
Actual result: It says “Generates 10 CPU” but “CPU per day: 12”.

Of course, the same thing happens with other CPU types.

---

PS: I know this is a deja vu but this bug is subtly different than #231, as it affects a different window.

**Comment by Xenega** [comment]
It's not a bug. It show the base CPU of the item. CPU per day display taking account the modifiers.

Two different informations.

**Comment by nthykier** [comment]
Perhaps we can choose a different text string to make this more clear?  Like `Generates X CPU before any modifiers`? (Less unwieldy suggestions welcome)

**Comment by Wuzzy2** [comment]
Or "Generates X CPU (+Y%)” or “Generates CPU (+zone bonus)”

**Comment by LW-archlinux** [comment]
Maybe `Basic Output` for the first value and `Usable Output` for the second will work .

The help text about this screen should explain Basic Output shows the value without productivity modifiers applied, while Usable Output does take into account productivity modifiers.
