### ISSUE TITLE
“CPU per day:” no longer translated

### ISSUE THREAD

**Issue by Wuzzy2** [singularity/singularity#244]
“CPU per day:” is no longer translated since 1e72977364a7a9c0d716b2d9f3e08cc9b3dc3d53. It *was* translated before.

This string appears when opening a base.

**Comment by Xenega** [comment]
It's not a bug. The translation are just not present. I updated the po and pot for you. But basically we should do it more than one or two time by week (until we separate translations in another repos).

**Comment by Wuzzy2** [comment]
Whoops, my bad. And I even grepped for the string and thought I found it verbatim in both sources in PO files. I must have missed the addition of the %d to the string. Sorry.
