### ISSUE TITLE
Call for translations for singularity 1.0 (deadline for finished submission: 2020-07-01)

### ISSUE THREAD

**Issue by nthykier** [singularity/singularity#251]
We are planning a release of singularity 1.0 and hope you would like to contribute translations of the game into your native language (we are looking for updates to existing translations but also accept translations to new languages as well).

 * If you intend to submit a translation (whether new or an update), please let us know as early as possible along with when you expect to have it ready.  That will help us with the planning and tracking of pending translations. :)

**Pending translations**

- [x] German (Wuzzy2)
- [ ] Brazilian Portuguese (MestreLion)
- [x] Scottish Gaelic (gunchleoc)
- [ ] Your translation here? :)

# Translation - the singularity specific part

Translation is done via 4 GNU po files placed in `singularity/i18n/lang_ll_LL/` based on the 4 POT files in `singularity/i18n/` (file names `data_str.po(t)`, `knowledge.po(t)`, `messages.po(t)` and `story.po(t)`.

(Optionally) You can use `utils/gettext-singularity` to help you setup the .po files for you assuming you have the relevant prerequisites installed (see `utils/gettext-singularity --help` for tools needed beyond the python3 related dependencies for running singularity).  Though any tool that can create a PO file from a POT file should work provided that you save the PO file in the correct directory with the correct name.

Once you have the translations done, please submit them via a pull request.

You are also very welcome to submit corrections to the original text if you discover typo's etc. while working on the translation.  We recommend that these are done in a separate commit from the translation itself.

**Comment by nthykier** [comment]
Ping: @Wuzzy2, @MestreLion, @eaglexboy and @DrMoriarty - you appear to be listed as last translator for one or more languages and I hope you are interested in updating the translations for those languages. :)

**Comment by MestreLion** [comment]
Thanks for the call! I'll fetch the current repo, update the Brazilian Portuguese translations and send a pull request in 2 days

**Comment by nthykier** [comment]
Hi @MestreLion  How is it looking with the translation? :)

**Comment by MestreLion** [comment]
> Hi @MestreLion How is it looking with the translation? :)

I wasn't able to finish it yet, and it will take a few more days. Is there a deadline for releasing a new version?

**Comment by nthykier** [comment]
There is no hard deadline at the moment.  Though I am trying to keep the steam up for finishing the release, so we can get the long overdue 1.0 release out to players looking forward to it (see also #249)

**Comment by gunchleoc** [comment]
I have some truncation/overlap issues in my translation. I'll take a stab at fixing those before I start filing issues.

**Comment by nthykier** [comment]
Many thanks for your translations and your improvements. :)  I have merged all but one, where I requested @Xenega's review to see if they have an alterative solution. :)

**Comment by nthykier** [comment]
@Wuzzy2 and @MestreLion: FYI: I have regenerated POT and PO files after @gunchleoc's new branch to support ngettext/numerical translations.  This includes new strings in the "messages.po", which I hope you will have time to add translations for.

**Comment by Wuzzy2** [comment]
#288.

**Comment by nthykier** [comment]
Thanks for the update. :)  I will cut a release 1st of July (or when I have all pending translations; whichever comes first), so I have set a deadline for updated translations accordingly.

@MestreLion: FYI - you asked earlier if there was a deadline; there is now :)
