### ISSUE TITLE
Creating a sandbox using fake root makes files owned by root in the directory

### ISSUE THREAD

**Issue by TEMTLC** [singularity/singularity#255]
**Describe the bug**
Creating a sandbox using fake root makes files owned by root in the directory

**To Reproduce**

using singularity version 3.5.3-1.1.el7

steps to reproduce the behavior:
*To Reproduce**
singularity build --fakeroot --sandbox centos-test/ centos-test-base.sif

**Expected behavior**
I expected to get a sandbox created where my id could then single step commands to build tensorflow using bazel

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 3.7]

**Additional context**

**Comment by TEMTLC** [comment]
Build target already exists. Do you want to overwrite? [N/y] y
WARNING: The underlying filesystem on which resides "/gpfs/home/millerte/biometrics/containers/docker/containers-docker-base/centos/centos-test" won't allow to set ownership, as a consequence the sandbox could not preserve image's files/directories ownerships

**Comment by TEMTLC** [comment]
What is the correct way to build a sandbox using fakeroot from an existing container?

**Comment by nthykier** [comment]
Hi @TEMTLC,

I think you got the "wrong" singularity project.  :) This is a game written in Python about an AI and has nothing to do with biometrics nor tensorflow (plus we have not even released `v1.0` yet despite being a 10+ year old project).
