### ISSUE TITLE
Truncated text on Knowledge screen

### ISSUE THREAD

**Issue by gunchleoc** [singularity/singularity#270]
**Describe the bug**
The highlighted item on the list in the screenshot should say `Pròiseact: Teòirim na do-dhèantachd`, but only `Pròiseact: Teòirim na` is visible.

![table-text-resize-bug](https://user-images.githubusercontent.com/4095570/83335415-8c46ae00-a2a4-11ea-9893-345124108d34.png)

**To Reproduce**
1. Select "Gàidhlig" as your language
2. Select "Eòlas" on the bottom right (Knowledge)
3. Scroll down until you see the entry

**Expected behavior**
The font size should have been reduced to fit the text.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Python version 3.6.9
 - Version aac0c8df4ed2aef3a3b80777617c71d256aa3f01

**Comment by nthykier** [comment]
@Xenega Do you want to look at this one? :)

**Comment by Xenega** [comment]
Basically we need to stop divide the screen into three to let more space for listbox text.

I will create a pull request about it.
