### ISSUE TITLE
Repeating text input with accented vowels

### ISSUE THREAD

**Issue by gunchleoc** [singularity/singularity#281]
**Describe the bug**
When I type `è` on a German keyboard into the savegame text dialog, the letter keeps repeating endlessly until I hit a button or another key.

**To Reproduce**
1. Install a German keyboard layout or an English International one - anything that needs 2 keypresses to combine a letter should do.
2. Start a Game
3. Click on MENU -> SAVE GAME
4. Type backquote followed by `e`
5. The text input field gets filled with an additional `è` on every event cycle

**Expected behavior**
Only 1 `è`

**Screenshots**
![repeating_accented_vowel](https://user-images.githubusercontent.com/4095570/84008947-6c7d4d00-a96a-11ea-9b6d-9dd11e4c3ad9.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.01 Tessa 64-bit
 - Python version: 3.6.9
 - Version: current master (e.g. https://github.com/singularity/singularity/commit/a9d136a5ed00420e4ca21cb4d915fa08d51ee762)

**Comment by nthykier** [comment]
Fixed in master.  Note that pygame 1 / SDL 1 has a bug with repeating accented vowels, so that is a known issue.

**Comment by gunchleoc** [comment]
Fix confirmed :)
