### ISSUE TITLE
Location screen - can't put base to sleep

### ISSUE THREAD

**Issue by gunchleoc** [singularity/singularity#282]
**Describe the bug**
If you build a new base, the on/off button is deactivated. Player can circumvent the bug, by selecting a different base and then selecting the new base, but this won't work if you have only 1 base.

**To Reproduce**

Go to the Antarctic in the attached savegame. The time capsule can't be put to sleep.

[Time Capsule.s2.zip](https://github.com/singularity/singularity/files/4765807/Time.Capsule.s2.zip)

**Comment by nthykier** [comment]
It cannot be reproduced via the save game (`save -> load` also "fixes" the issue)

**Comment by gunchleoc** [comment]
I have also have this happen when building stolen computer time - building those will be faster for testing than building a time capsule.

**Comment by nthykier** [comment]
Just to clarify, do you still have this issue after the recent commit that claims to close it?
