### ISSUE TITLE
Failure to run container as a different user

### ISSUE THREAD

**Issue by tashrifbillah** [singularity/singularity#295]
# Way to reproduce
```
singularity build --sandbox /tmp/centos7 docker://centos:7.5.1804
singularity shell -u trump centos7/
```

# Error
> FATAL:   failed to retrieved path for /tmp/trump: lstat /tmp/trump: no such file or directory

# Additional information
```vim
[tb571@pnl-z840-2 tmp]$ singularity --version
singularity version 3.2.1-1.1.el7
[tb571@pnl-z840-2 tmp]$ uname -a
Linux pnl-z840-2 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

# Goal
Run a singularity container as a different user than the user running the singularity process

**Comment by nthykier** [comment]
Tashrif Billah:
> # Way to reproduce
> ```
> singularity build --sandbox /tmp/centos7 docker://centos:7.5.1804
> singularity shell -u trump centos7/
> ```
> 
> # Error
>> FATAL:   failed to retrieved path for /tmp/trump: lstat /tmp/trump: no such file or directory
> 
> # Additional information
> ```vim
> [tb571@pnl-z840-2 tmp]$ singularity --version
> singularity version 3.2.1-1.1.el7
> [tb571@pnl-z840-2 tmp]$ uname -a
> Linux pnl-z840-2 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> # Goal
> Run a singularity container as a different user than the user running the singularity process
> 
> 
> 

Hi,

I think you got the wrong "singularity" project. :)  This project is a
game and got nothing to do with containers.  My best guess is that you
wanted https://sylabs.io/resources/support (although I am not entirely
sure).

Niels
