### ISSUE TITLE
Packaging/Setup collision

### ISSUE THREAD

**Issue by ghostshadow** [singularity/singularity#296]
The setup.py installs the `utils` package as a root level package, which causes very likely collisions with other python packages.
(For me specifically flowblade collides, which uses `import utils` in various modules, but that should probably be solved in a different way as well)

I am not sure, if the utils package is required for the game or just a development aid ... 
In the first case it should best be put below the singularity namespace, or in the latter case it should be excluded from install by more directly specifying the packages (i.e. manually or with filtering instead of plain find_packages).

**Comment by nthykier** [comment]
Indeed; `utils` is not required for running the game and it would make sense to omit it on install.  A PR for this would be very welcome if you have time and energy for it. :)

**Comment by nthykier** [comment]
Fixed by https://github.com/singularity/singularity/commit/05a3b9199120fdea8d7bcee3752c3eb0ef764742 as far as I can tell
