### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xspython** [singularity/singularity#301]
system version : redhat 7.4
singularity version: 3.7.3
singularity  build yade_ubantu20.0.4.sif  docker-archive://docker-prod:ubuntu20.04
./yade_ubantu20.0.4.sif 
Singularity> yade
Segmentation fault (core dumped)

docker run  -it docker-prod:ubuntu20.04
$ yade  
# stauts success

https://yade-dem.org/doc/installation.html

**Comment by nthykier** [comment]
Hi @xspython 

I am afraid you have found the wrong bug tracker - this "singularity" is a computer game. Based on your examples, I think you are looking for "yade" (https://gitlab.com/yade-dev) which also provides something called "singularity".

I am closing this issue as we cannot fix bugs in the yade singularity component - I recommend you re-file your issue in the yade bug tracker.
