### ISSUE TITLE
malloc_consolidate(): unaligned fastbin chunk detected

### ISSUE THREAD

**Issue by ryantm** [singularity/singularity#305]
**Please include the log file**
If the "An error has occurred"-dialog mentions a log file, then please include the log file to this report.  A simple "copy-paste" of the log file contents into the report is sufficient.

```
 singularity
Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.9.6 (default, Jun 28 2021, 08:57:49) [GCC 10.3.0]
pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/ryantm/.local/share/singularity/log/error.log (lazily created when something is logged)
malloc_consolidate(): unaligned fastbin chunk detected
Aborted (core dumped)
```

**Please include a savegame that can reproduce the issue**
If you can, please provide a savegame where it is easy to demonstrate the problem.

**To Reproduce**
If possible, please describe the steps to reproduce the behavior:

If applicable, please add screenshots to help explain your problem.

**Additional context**

**Comment by nthykier** [comment]
Hi,

Given your #304, I suspect this is de facto a duplicate of #304 caused by an underlying memory bug in pygame (either miscompiled or a code bug).

**Comment by EinstokFair** [comment]
Any progress with this bug? What are plans to diagnose it?

**Comment by rofl0r** [comment]
you can diagnose this bug yourself using valgrind or asan, since the error message clearly points to heap memory corruption as the cause.

**Comment by EinstokFair** [comment]
I don't have knowledge for that. So the opensource software will remain bugly.
