### ISSUE TITLE
Automation of repetetive actions

### ISSUE THREAD

**Issue by EinstokFair** [singularity/singularity#309]
I am playing "Very Easy" settings. From start I have 5000 money and want to rent 50 or 60 servers at start. I need 120 clicks to do that.
Later on base construction dialog it is possible to define number of computer to purchase for base. Why the same is not possible for rental actions of for hacking personal computers?

**Comment by nthykier** [comment]
The premise of the game is that you want to hide and therefore has a few bases as possible.  It is true that the game lets you abuse the grace period of Very Easy but it is not something we want to optimize the UI for. As soon as the grace period is over, deploying 50 bases will be a net loss to you as detection rates will increase considerably.
