### ISSUE TITLE
malloc_consolidate(): unaligned fastbin chunk detected

### ISSUE THREAD

**Issue by EinstokFair** [singularity/singularity#310]
$ singularity --theme=vector --nosound
Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.9.5 (default, Jul 15 2021, 11:19:42) [GCC 10.3.0]
pygame 2.0.1 (SDL 2.0.10, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/user/.local/share/singularity/log/error.log (lazily created when something is logged)
malloc_consolidate(): unaligned fastbin chunk detected
Aborted (core dumped)

**Comment by EinstokFair** [comment]
Oh, duplicate of https://github.com/singularity/singularity/issues/305, sorry

**Comment by nthykier** [comment]
Ok, closing it as a duplicate.

**Comment by EinstokFair** [comment]
$ gdb -c ./core.singularity.1000.316097c4c3964844b8d7dc2e925f61ca.2794939.1630465132000000
    GNU gdb (Gentoo 10.1 vanilla) 10.1
    Copyright (C) 2020 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    Type "show copying" and "show warranty" for details.
    This GDB was configured as "x86_64-pc-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <https://bugs.gentoo.org/>.
    Find the GDB manual and other documentation resources online at:
        <http://www.gnu.org/software/gdb/documentation/>.
    
    For help, type "help".
    Type "apropos word" to search for commands related to "word".
    [New LWP 2794945]
    [New LWP 2794942]
    [New LWP 2794943]
    [New LWP 2794946]
    [New LWP 2794948]
    [New LWP 2794950]
    [New LWP 2794951]
    [New LWP 2794947]
    [New LWP 2794949]
    [New LWP 2794952]
    [New LWP 2794953]
    [New LWP 2794954]
    [New LWP 2794955]
    [New LWP 2794944]
    [New LWP 2794939]
    Core was generated by `/usr/bin/python3.9 /usr/bin/singularity'.
    --Type <RET> for more, q to quit, c to continue without paging--
    Program terminated with signal SIGABRT, Aborted.
    #0  0x00007f97d8eff891 in ?? ()
    [Current thread is 1 (LWP 2794945)]
    (gdb) backtrace full
    #0  0x00007f97d8eff891 in ?? ()
    No symbol table info available.
    #1  0x000000000e017407 in ?? ()
    No symbol table info available.
    #2  0x0000000000000000 in ?? ()
    No symbol table info available.

**Comment by EinstokFair** [comment]
some other error text, should i create one more bug?

	$ valgrind  --leak-check=full  --show-leak-kinds=all --log-file="test00" singularity 
	Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
	Running under Python 3.9.6 (default, Aug 31 2021, 06:56:05) [GCC 10.3.0]
	pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
	Hello from the pygame community. https://www.pygame.org/contribute.html
	The error-log configured as /home/user/.local/share/singularity/log/error.log (lazily created when something is logged)
	X Error of failed request:  BadWindow (invalid Window parameter)
	  Major opcode of failed request:  3 (X_GetWindowAttributes)
	  Resource id in failed request:  0x800000e
	  Serial number of failed request:  932
	Current serial number in output stream:  935

**Comment by rofl0r** [comment]
you need to compile pygame with -O0 -g3, then use 

valgrind --track-origins=yes --trace-children=yes and eventually --leak-check=full though i dont think leak related options are required. X error messages are irrelevant, you need to look for messages related to invalid writes and the like

**Comment by EinstokFair** [comment]
1) Why do I need to use "trace children", if singularity game is the single python process which doesn't start others?

2) what -g3 option means ?
https://gcc.gnu.org/onlinedocs/gcc/Invoking-GCC.html
https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html#Debugging-Options

    -glevel
    -ggdblevel
    Level 3 includes extra information, such as all the macro definitions present in the program. Some debuggers support macro expansion when you use -g3. 

do i need -g3 or -ggdb3 or both and why?

3) if X error message is irrelevant here, then may be other bug which it is relate to?

**Comment by rofl0r** [comment]
> Why do I need to use "trace children", if singularity game is the single python process which doesn't start others?

because SDL starts a number of threads

**Comment by EinstokFair** [comment]
Starting a thread don't require process forking.

https://valgrind.org/docs/manual/manual-core.html#manual-core.pthreads
«Valgrind serialises execution so that only one (kernel) thread is running at a time. This approach avoids the horrible implementation problems of implementing a truly multithreaded version of Valgrind»

here is some [log example](https://gist.github.com/EinstokFair/3c6d421c613d32044788f20a1bcb0590) (but for another bug). I need some luck to reproduce this one (it is more rare, but still reproduced three times already at my machine).

**Comment by JensKorte** [comment]
I have the same problem. When deactivating ccache the error message changes but still the game crashes within minutes. It seems to me, when playing the easiest mode, creating many servers (20-50) speeds the up the crash. My system: RaspberryPi 400, Gentoo 64 bit (arm64).
