### ISSUE TITLE
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault on Gentoo

### ISSUE THREAD

**Issue by EinstokFair** [singularity/singularity#311]
**Please include the log file**
    $ singularity 
    Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
    Running under Python 3.9.6 (default, Aug 31 2021, 06:56:05) [GCC 10.3.0]
    pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
    Hello from the pygame community. https://www.pygame.org/contribute.html
    The error-log configured as /home/user/.local/share/singularity/log/error.log (lazily created when something is logged)
    Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
    Python runtime state: initialized
    
    Current thread 0x00007faf429fb640 (most recent call first):
    <no Python frame>
    
    Thread 0x00007faf55cfb740 (most recent call first):
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 272 in handle
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 231 in show
      File "/usr/lib/python3.9/site-packages/singularity/code/screens/message.py", line 119 in show
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 125 in call_dialog
      File "/usr/lib/python3.9/site-packages/singularity/code/screens/message.py", line 44 in show_list
      File "/usr/lib/python3.9/site-packages/singularity/code/screens/map.py", line 639 in on_tick
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 405 in call_handlers
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 390 in handle
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 231 in show
      File "/usr/lib/python3.9/site-packages/singularity/code/safety.py", line 64 in safe_call
      File "/usr/lib/python3.9/site-packages/singularity/code/screens/map.py", line 580 in show
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 125 in call_dialog
      File "/usr/lib/python3.9/site-packages/singularity/code/screens/main_menu.py", line 104 in new_game
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/button.py", line 247 in activated
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/button.py", line 213 in activate_with_sound
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/button.py", line 199 in handle_event
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 405 in call_handlers
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 390 in handle
      File "/usr/lib/python3.9/site-packages/singularity/code/graphics/dialog.py", line 231 in show
      File "/usr/lib/python3.9/site-packages/singularity/__init__.py", line 382 in main
      File "/usr/bin/singularity", line 33 in <module>
    Aborted (core dumped)

[valgrind --track-origins=yes singularity](https://gist.github.com/EinstokFair/3c6d421c613d32044788f20a1bcb0590)
[valgrind  --leak-check=full --show-leak-kinds=all](https://gist.github.com/EinstokFair/8f865a185c293dd95f670d745ead1917)

**Additional context**
This happened after installing pygame and numpy with pip (by [proposition](https://github.com/singularity/singularity/issues/304#issuecomment-908927806) of @nthykier), as described [here](https://github.com/singularity/singularity/issues/304#issuecomment-909736067)

Also I tried to do [this](https://gamedev.stackexchange.com/questions/24296/fatal-python-error-pygame-parachute-segmentation-fault-when-using-pygame-and)

    $ python
    Python 3.9.6 (default, Aug 31 2021, 06:56:05) 
    [GCC 10.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pygame
    pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
    Hello from the pygame community. https://www.pygame.org/contribute.html
    >>> print(pygame.__version__)
    2.0.1
    >>> pygame.init()
    (7, 0)
    >>> import numpy
    >>> print(numpy.__version__)
    1.21.2

Which show no error message.

I can't distinguish which modules are used - system or from pip, because they have same version in both locations.
https://stackoverflow.com/questions/247770/how-to-retrieve-a-modules-path

    >>> print(numpy.__file__)
    /home/user/.local/lib/python3.9/site-packages/numpy/__init__.py
    >>> print(pygame.__file__)
    /home/user/.local/lib/python3.9/site-packages/pygame/__init__.py

«please check if they already have a bug in their bug tracker (for pygame) about this crash?»
No, [they don't have](https://bugs.gentoo.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=IN_PROGRESS&bug_status=RESOLVED&bug_status=VERIFIED&f0=OP&f1=OP&f2=alias&f3=short_desc&f4=CP&f5=CP&j1=OR&list_id=5768449&o2=substring&o3=substring&query_format=advanced&short_desc=pygame_parachute&short_desc_type=allwordssubstr&v2=pygame_parachute&v3=pygame_parachute).

Bugtracker of pygame itself:
https://github.com/pygame/pygame/issues
( I don't know what to write there, and why I should write there instead of any other dependency bugtracker)

So, I done anything what I can.

**Comment by EinstokFair** [comment]
$ valgrind  --leak-check=full  --show-leak-kinds=all --log-file="test01" singularity
	...
	==2946352== 32 bytes in 1 blocks are still reachable in loss record 997 of 4,584
	==2946352==    at 0x4844581: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
	==2946352==    by 0x4DCEB07: _dlerror_run (dlerror.c:148)
	==2946352==    by 0x4DCE363: dlclose (dlclose.c:46)
	==2946352==    by 0x6FAA921: UnloadPulseAudioLibrary (SDL_pulseaudio.c:145)
	==2946352==    by 0x6FAA921: PULSEAUDIO_Deinitialize (SDL_pulseaudio.c:759)
	==2946352==    by 0x6EBF112: SDL_AudioQuit_REAL (SDL_audio.c:1609)
	==2946352==    by 0x6EB98DC: SDL_QuitSubSystem_REAL (SDL.c:358)
	==2946352==    by 0x6C9B250: _pg_quit (in /home/user/.local/lib/python3.9/site-packages/pygame/base.cpython-39-x86_64-linux-gnu.so)
	==2946352==    by 0x6C9B2A9: pygame_parachute (in /home/user/.local/lib/python3.9/site-packages/pygame/base.cpython-39-x86_64-linux-gnu.so)
	==2946352==    by 0x4C2B8FF: ??? (in /lib64/libc-2.33.so)
	==2946352==    by 0x86F418F: pgEvent_FillUserEvent (in /home/user/.local/lib/python3.9/site-packages/pygame/event.cpython-39-x86_64-linux-gnu.so)
	==2946352==    by 0xA08D42B: timer_callback (in /home/user/.local/lib/python3.9/site-packages/pygame/time.cpython-39-x86_64-linux-gnu.so)
	==2946352==    by 0x6F33FA3: SDL_TimerThread (SDL_timer.c:166)
	...
	==2946352== 48 bytes in 2 blocks are still reachable in loss record 2,425 of 4,584
	==2946352==    at 0x483F7B5: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
	==2946352==    by 0xC5A24E5: ??? (in /usr/lib64/libX11.so.6.4.0)
	==2946352==    by 0xC5A2B0E: _XSend (in /usr/lib64/libX11.so.6.4.0)
	==2946352==    by 0xC5A316B: _XReply (in /usr/lib64/libX11.so.6.4.0)
	==2946352==    by 0xC59EB8A: XSync (in /usr/lib64/libX11.so.6.4.0)
	==2946352==    by 0xC57FB1A: XCloseDisplay (in /usr/lib64/libX11.so.6.4.0)
	==2946352==    by 0x6FB7C13: X11_DeleteDevice (SDL_x11video.c:106)
	==2946352==    by 0x6F83524: SDL_VideoQuit_REAL (SDL_video.c:2991)
	==2946352==    by 0x6EB98FC: SDL_QuitSubSystem_REAL (SDL.c:370)
	==2946352==    by 0x6C9B229: _pg_quit (in /home/user/.local/lib/python3.9/site-packages/pygame/base.cpython-39-x86_64-linux-gnu.so)
	==2946352==    by 0x6C9B2A9: pygame_parachute (in /home/user/.local/lib/python3.9/site-packages/pygame/base.cpython-39-x86_64-linux-gnu.so)
	==2946352==    by 0x4C2B8FF: ??? (in /lib64/libc-2.33.so)

**Comment by nthykier** [comment]
Most likely related to pygame/pygame#3128. At this point, the only known work around is to downgrade your pygame version.

**Comment by illume** [comment]
Hi. This should be fixed in pygame==2.5.0

**Comment by thePalindrome** [comment]
It has not for me.

```
/tmp/singularity $./run_singularity.sh 
Singularity 1.00 (commit: v1.00-8-g4df079f)
Running under Python 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
<frozen importlib._bootstrap>:241: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
pygame 2.5.0 (SDL 2.26.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/[redacted]/.local/share/singularity/log/error.log (lazily created when something is logged)
./run_singularity.sh: line 8: 422165 Segmentation fault      (core dumped) PYTHONPATH="${PYPATH}" "${PYTHON}" -m singularity "$@"
```

Running in Fedora 38

**Comment by thePalindrome** [comment]
Here's a gdb bt:

```
Thread 2 "SDLTimer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffef08456c0 (LWP 428173)]
0x00007ffff6caeac5 in pgEvent_FillUserEvent (e=0x1, event=0x7ffef0844d10) at src_c/event.c:665
Downloading source file /usr/src/debug/pygame-2.5.0-1.fc38.x86_64/src_c/event.c
665         Py_INCREF(e->dict);                                                                                                                                                                                                                                                                                             
Missing separate debuginfos, use: dnf debuginfo-install python3-3.11.4-1.fc38.x86_64
(gdb) bt
#0  0x00007ffff6caeac5 in pgEvent_FillUserEvent (e=0x1, event=0x7ffef0844d10) at src_c/event.c:665
#1  0x00007ffff6812829 in timer_callback (interval=33, param=<optimized out>) at src_c/time.c:234
#2  0x00007ffff68bf3b8 in SDL_TimerThread (_data=0x7ffff69fc140 <SDL_timer_data>) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/timer/SDL_timer.c:168
#3  0x00007ffff69726c6 in SDL_RunThread (thread=<optimized out>) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/thread/SDL_thread.c:305
#4  RunThread (data=0x555555c5f170) at /usr/src/debug/SDL2-2.26.3-1.fc38.x86_64/src/thread/pthread/SDL_systhread.c:77
#5  0x00007ffff78ae907 in start_thread (arg=<optimized out>) at pthread_create.c:444
#6  0x00007ffff7934870 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

I'm not sure if this is the same bug or not, but it causes a segfault from pygame, so it might be

**Comment by illume** [comment]
Hrmm. I can't repo on my machine anymore but I tried something else...

Does this fix it for you?

```
python -m pip install git+https://github.com/pygame/pygame.git@33f2eedfc56a4315f3a3e8babd91261610a39328
```

**Comment by thePalindrome** [comment]
Unfortunately not:
```
/tmp/singularity/singularity/code/mixer.py:49: RuntimeWarning: use mixer: No module named 'pygame.mixer'
(ModuleNotFoundError: No module named 'pygame.mixer')
  pygame.mixer.pre_init(*soundargs, buffer=desired_soundbuf)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/singularity/singularity/__main__.py", line 26, in <module>
    main()
  File "/tmp/singularity/singularity/__init__.py", line 345, in main
    mixer.preinit(desired_soundbuf)
  File "/tmp/singularity/singularity/code/mixer.py", line 49, in preinit
    pygame.mixer.pre_init(*soundargs, buffer=desired_soundbuf)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.local/lib/python3.11/site-packages/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ModuleNotFoundError: No module named 'pygame.mixer')
```
I'm guessing that particular repo setup meant that it didn't build with the mixer?

I have the SDL_mixer-devel package, so it should've picked it up

**Comment by illume** [comment]
Thanks for the help. I appreciate it :)

I guess it’s the SDL mixer “2” devel package.

**Comment by thePalindrome** [comment]
Ah, didn't realize you migrated to SDL2 with this!

Well, I gave it some tests, which went well. It's hard because I'm trying to prove that a random thing *won't* happen, but it does seem like it's working! I'll give it more tests tomorrow though.

**Comment by illume** [comment]
Awesome sauce. Thanks again.
