### ISSUE TITLE
how to run from source windows 

### ISSUE THREAD

**Issue by ReTr09761** [singularity/singularity#315]
I've looked at and read readme.txt and cant see any way to run from source on windows

**Comment by nthykier** [comment]
Hi,

You have to install python3 plus the dependencies - presumably via pip - and then run `python3 -m singularity` from the git checkout / source root.  Alternative you can try to leverage WSL2 and then the Linux based instructions assuming the WSL2 support is good enough for graphical applications now.

Mind you, I have tried neither and I cannot offer concrete guidance.  I am speaking from a theoretically point of view.  If you figure it out and the instructions are not too complicated, you are welcome to provide a short guide that we can include in the readme.

**Comment by Eneocho** [comment]
If you install the dependencies and python, you can just cmd, navigate to the folder and do that command.
I can confirm it works.
![image](https://github.com/singularity/singularity/assets/67024428/27b6c33f-425d-4f3a-875d-cf9d0e726024)
In my case, i don't have to specify python3, but it works all the same.
Install python.
Install the dependencies via pip.
Download or clone the repo.
CMD and navigate to that folder, then run the command.
That'd be the simplest, albeit not smartest way to run the game.
