### ISSUE TITLE
Signing key expired

### ISSUE THREAD

**Issue by svenstaro** [singularity/singularity#325]
As of this writing, the signing key of [release 1.00](https://github.com/singularity/singularity/releases/tag/v1.00) has expired. Perhaps a new release with a new (and importantly, cross-signed) signature could be made?

**Comment by nthykier** [comment]
Hi,

The key had its expiry date bumped a while back (before its expiry), so it "WFM" locally. I am going to export the key locally once I figured out the magic GPG runes.

**Comment by nthykier** [comment]
This is the copy of the key I have locally.

[key.txt](https://github.com/singularity/singularity/files/9130446/key.txt)

**Comment by svenstaro** [comment]
Can you put that key into an official release or switcheroo the files on that?

**Comment by nthykier** [comment]
I can add it to the v1.0 release if that would help

**Comment by svenstaro** [comment]
Do leave the old key up though, don't actually replace the files. Just add new appropriately named files.

**Comment by nthykier** [comment]
It is exactly the old key (with bumped expiry).  I have added it to the release page as `signing-key.asc`

**Comment by svenstaro** [comment]
Thanks! That's good enough for me but I suggest also republishing the key to keyservers.

**Comment by nthykier** [comment]
Thanks for confirming. I have uploaded it two `hkp://keys.openpgp.org` as well. :)
