### ISSUE TITLE
Add topic to singularity repository

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#33]
Add topic to singularity repository.

**Comment by rofl0r** [comment]
?

**Comment by Xenega** [comment]
https://help.github.com/articles/about-topics/

**Comment by MestreLion** [comment]
What topics do you suggest we add?

**Comment by Xenega** [comment]
python game pygame, would be a good start.

**Comment by Quix0r** [comment]
I would also add `strategy`.

**Comment by MestreLion** [comment]
Done, thanks for the suggestions!
