### ISSUE TITLE
Crash bug: can't get singularity to bind/execute my trinity image. singularity command responds with the same warning message - core dumped

### ISSUE THREAD

**Issue by oowynn** [singularity/singularity#334]
I am trying to use the trinity singularity image. 
I have followed the SingularityCE installation instructions and I have also installed GO. 

When I use singularity as a command I get this message in response, even if I check the version.

$ singularity exec trinityrnaseq.v2.15.1.simg
Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
Running under Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
pygame 2.1.2 (SDL 2.0.20, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
The error-log configured as /home/ubuntu/.local/share/singularity/log/error.log (lazily created when something is logged)
Segmentation fault (core dumped)

Thank you in advance :)

**Comment by nthykier** [comment]
oowynn:
> I am trying to use the trinity singularity image.
> I have followed the SingularityCE installation instructions and I have also installed GO.
> 
> When I use singularity as a command I get this message in response, even if I check the version.
> 
> $ singularity exec trinityrnaseq.v2.15.1.simg
> Singularity 1.00 (commit: 2ebc2f3f2059b96885416167363bde2e27ece106)
> Running under Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
> pygame 2.1.2 (SDL 2.0.20, Python 3.10.12)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> The error-log configured as /home/ubuntu/.local/share/singularity/log/error.log (lazily created when something is logged)
> Segmentation fault (core dumped)
> 
> 
> Thank you in advance :)
> 

Hi,

There is no *trinity singularity image* nor a SingularityCE plus this 
game does not need `GO`.

I suspect you have mixing "singularity endgame" (this game) with another 
singularity project (such as https://github.com/sylabs/singularity). 
Particular, given the command line you are showing, I suspect you wanted 
"a" singularity involving containers (I think that is the sylabs one I 
linked too, but honestly I do not know)
  to run some container feature.

(If this is the case, you would not be the first to make this mistake. 
It is an unfortunate name clash)
