### ISSUE TITLE
[Windows 11] Game constantly makes a popup (like you clicked on ESC)

### ISSUE THREAD

**Issue by MrWillow** [singularity/singularity#341]
**Describe the bug**

After staring the game makes a dialogue (with 'save as', quit, etc). Clicking it away works for a very short time, then it is back
I downloaded from here:
https://github.com/singularity/singularity-windows/archive/v0.30c.zip

**To Reproduce**
1. Get some Windows 11 64bit machine up.
2. Download windows version: https://github.com/singularity/singularity-windows/archive/v0.30c.zip
3. play the game
4. nonstop popups

**Expected behavior**
No popups.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 64bit 
 - precomplided version: v0.30c.zip

**Additional context**
Used to work like a charm on my Win 10 machine

**Comment by nthykier** [comment]
Hi

The v0.30c is quite old. Can you reproduce this problem with the v1.0.0? https://github.com/singularity/singularity/releases

**Comment by MrWillow** [comment]
Ah, thanks! Version1.0.0 doesn't have this issue.

**Comment by nthykier** [comment]
Glad to hear that fixed it. :)
