### ISSUE TITLE
`np.cast` was removed in the NumPy 2.0 release

### ISSUE THREAD

**Issue by hexagonrecursion** [singularity/singularity#346]
**Please include the log file**

[error.log](https://github.com/user-attachments/files/16431567/error.log)

**Please include a savegame that can reproduce the issue**

Not necessary: happens every time in a freshly started game

**To Reproduce**
1. Click "new game"
2. Click "impossible"
3. Click "skip"
4. Click on Australia
5. Click "new base"
6. Crash

**Additional context**

https://numpy.org/doc/stable/numpy_2_0_migration_guide.html

| removed member | migration guideline |
|-|-|
| cast | Use np.asarray(arr, dtype=dtype) instead. |

Workaround: install an older version of numpy

**Comment by nthykier** [comment]
Thanks, should be fixed in the main branch! Let me know you still have issues with numpy 2.0 (I do not have it handy, so I did not do a full test here).
