### ISSUE TITLE
Earth background theme

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#47]
Finish theme options for the new earth background.

**Comment by Xenega** [comment]
After testing I think I prefer the vector image. So I think I will make it the default. 

You can test it with [testing/background](testing/background). What do you think ?

**Comment by rofl0r** [comment]
do you have screenshots ?

**Comment by Xenega** [comment]
There!
![vector](https://user-images.githubusercontent.com/5785857/39100688-04131790-468e-11e8-9981-dc2639305446.png)

**Comment by rofl0r** [comment]
thanks! i for my part prefer the retro look of the existing map (it's similar to the globe of the game `UFO - Enemy Unknown`)

**Comment by Quix0r** [comment]
This more looks like the world map from defcon game / War Games movie. But in my view it would be cool to have some theme support and have both, legacy and this background available.
