### ISSUE TITLE
pickle is insecure

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#52]
The python module pickle is very insecure. We use a white list and it mitigate the danger but it's not impossible and very hard to know if we have a security issue. Object can leak a functionality enough powerful to create a attack. 

IMHO, we should remove pickle and use a other system to save data. Less head scratch.

**Comment by rofl0r** [comment]
what security issue does this represent, other than a malicious savegame could be shared which executes random stuff on the victim's python install ?

**Comment by Xenega** [comment]
None. The issue is limited to execute random stuff with python. (But that's already a big problem)

**Comment by nthykier** [comment]
What do we want to replace pickle with?  From a quick glance, we will need two things:

A fast/cheap way of determining the save game version (needed by the savegame dialog) and a generic serialization format for the rest (supporting basic types such as strings, dicts and strings as a minimum).

This could be doable with something like a single line header identifying the file as a savegame plus its version followed by a payload of e.g. JSON or YAML (the latter with its safe variant of dump+load).

Do we want to go in that direction or are we looking for something different?
