### ISSUE TITLE
Fullscreen doesn't handle os shortcut.

### ISSUE THREAD

**Issue by Xenega** [singularity/singularity#58]
This is a problem with SDL and fullscreen. 
- Alt-Tab doesn't work. 
- Screenshot doesn't work.
...

**Comment by rofl0r** [comment]
i forget, can one switch from/to fullscreen using the standard ALT-enter keys or F11 ?

**Comment by Xenega** [comment]
No, but it's a good idea to implement it.

**Comment by Xenega** [comment]
I implemented it in 9d92c1b.

**Comment by rofl0r** [comment]
the linked commit seems to have only a couple translation changes.

**Comment by Xenega** [comment]
Ah sorry. It's 7634fc9.

**Comment by Xenega** [comment]
No solution in pygame 1.9 so I close it.
