### ISSUE TITLE
Feature proposal: Make music optional

### ISSUE THREAD

**Issue by funkyfuture** [singularity/singularity#6]
though the soundtrack certainly contributes well to the atmosphere, it'd be a charm if it could be triggered on/off. or even have an adjustable volume.

**Comment by MestreLion** [comment]
There is already an option in the Options Screen to toggle *sound* on/off, which also mutes the music soundtrack. Do you suggest to make independent toggles for music and sound "effects"?

If so, I have considered that in the past, but since the only sound effect in the game is the mouse click, I assume the current Sound toggle is only useful for the music

**Comment by MestreLion** [comment]
The adjustable volume is a nice idea indeed :)

**Comment by funkyfuture** [comment]
oh, it turned out that it needs a restart of the game to take the toggling of sound effect.
due to another expectation i came to the conclusion that music can't be toggled.

a segregation of sound and music may motivate to add some more effects.

**Comment by MestreLion** [comment]
That was all fixed in commits b690200b6f057820c6144f02297e8b55b2394e5f , 24bbab6374a7ea23bd3fbf792f4427512ff9afb4 and 67b3ef5f0b37cb4a2104c73f108a0b12fc82d59b

Try the game from the git repository instead of the (now ancient) release, there were many fixes since then, specially regarding options.

**Comment by funkyfuture** [comment]
great. the immediate change of toggling sounds does work. but there is no music at all.

**Comment by MestreLion** [comment]
Have you downloaded the music as well? When cloning the git repository you need to manually check out the soundtrack, as the music files are hosted in a distinct repository from the game code, at https://github.com/singularity/singularity-music (it's a git submodule actually). 

There are instructions at both https://github.com/singularity/singularity/tree/master/music and  https://github.com/singularity/singularity-music , and the relevant part is:

>From the singularity root directory, run:
>
>git submodule update --init music/singularity-music

You can also just drop some MP3s at `~/.local/share/singularity/music` (also the preferences dir, either the new one at `~/.config/singularity/music` or the legacy `~/.endgame/music`, will work just fine), but I personally find the `git submodule` approach much better, as it downloads the music inside the game root directory

**Comment by funkyfuture** [comment]
thanks, of course i missed that part.
