### ISSUE TITLE
The IRC channel is abandoned

### ISSUE THREAD

**Issue by ElonSatoshi** [singularity/singularity#63]
I believe the website says there's an IRC channel at #singularity on oftc. But I'm the only one there. Can you fix this issue by joining that channel and/or mentioning it in the README.md?

**Comment by Xenega** [comment]
I has never known the channel existed. I dunno where you found it... :o 
I will try to contact OFTC admins to revive the channel. But I don't think we will be a lot.

**Comment by sunfall** [comment]
nthykier and I hang out there regularly now, and Xenega (and anyone else) is welcome to come by as well.  I was the sole person in the IRC channel for many years and finally stopped showing up after a certain point. :P

**Comment by ElonSatoshi** [comment]
Great! I just joined. Now can the channel be mentioned in the README.md?

**Comment by Xenega** [comment]
Done.
