### ISSUE TITLE
Minor bug: Double keypress in info menu and sliders

### ISSUE THREAD

**Issue by ElonSatoshi** [singularity/singularity#65]
How to reproduce the issue:

1. Start the latest version of Singularity
2. Start a new game
3. Build 2 or more bases on any country
4. Click on one of the bases, then click the 'Open base' button.
5. Press and release the left or right arrow key.
6. Expectation: A single clicking sound, and you see info about the next base. Reality: It scrolls through the bases once when you press the key down, then again when you release the key.
7. Exit the list and the info dialogs, then click Research/tasks
8. Select one of the tasks/researches and press and release the right arrow key.
9. Expectation: the slider moves to the right adding 10 cpu. Reality: it does this twice, once when you press the key and once when you release the key.

I'm not sure if this is just for the slider and menu or if it's a universal bug on the left and right arrow keypresses.

**Comment by rofl0r** [comment]
sounds like a bug, i.e. the same code is fired on both the "press" and "release" events, when it should only be fired from one of them (which one of the 2 makes more sense could be evaluated by comparing which one feels more "natural")

**Comment by Xenega** [comment]
I cannot reproduce the bug. I think it can be a bug related to pygame. I have myself problem with keypress (no keypress until I restart the game) and I found the problem come from pygame.

**Comment by Xenega** [comment]
Without confirmation, this bug is closed.
