### ISSUE TITLE
GNU GPL is not included in the repository

### ISSUE THREAD

**Issue by F3nd0** [singularity/singularity#67]
For its application, the GNU General Public License must be included whole, verbatim. Commit [`96c61f017be9a0b4dc3f08ff6202b55b40bc039a`](https://github.com/singularity/singularity/commit/96c61f017be9a0b4dc3f08ff6202b55b40bc039a) has removed a part of this licence, thus creating a derivative licence, which should not be called the GNU GPL, as per [this notice](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOmitPreamble). This may be corrected by anyhow reverting the commit.

**Comment by Xenega** [comment]
I was wronged by this old issue : https://code.google.com/archive/p/endgame-singularity/issues/139
Thanks.
