### ISSUE TITLE
Have to manually create prefs.dat the first time I run the program.

### ISSUE THREAD

**Issue by rcriii42** [singularity/singularity#72]
Hi,

I'm running the program from source on a debian Linux installation with python 2.7, pygame and numpy installed. (FWIW version 0.3 from 2011 runs).

When running sulgularity.py or singularity.py -s, I get the following error message:
```
/home/rcriii/PycharmProjects/EIDataMunge/venv1/bin/python /home/rcriii/workspace/singularity/singularity.py
Traceback (most recent call last):
  File "/home/rcriii/workspace/singularity/singularity.py", line 23, in <module>
    import code.singularity
  File "/home/rcriii/workspace/singularity/code/singularity.py", line 262, in <module>
    g.load_themes()
  File "/home/rcriii/workspace/singularity/code/g.py", line 898, in load_themes
    themes_list = [name for name in os.listdir(themes_dir)
OSError: [Errno 2] No such file or directory: '/home/rcriii/.local/share/singularity/themes'

Process finished with exit code 1
```
Following the code along, it is looking for a file named "prefs.dat" in either "~/.config/singularity/1.0",   "~/.config/singularity" or "~/.endgame".  

If I create an empty prefs.dat file in ~/.config/singularity/1.0, the program runs, but has an error finding themes (separate issue created).

**Comment by Xenega** [comment]
Thanks for the report.

**Comment by rcriii42** [comment]
So where is the preferred location of prefs.dat? And will there be code at some point to add it if it does not exist? I can write that code but need the format.

**Comment by Xenega** [comment]
The code to add automatically the pref.dat exists, but was just bugged. Fixed now.
The preferred directory is ~/.config/singularity/1.0/.
