### ISSUE TITLE
Can not make a theme with custom font?

### ISSUE THREAD

**Issue by DrMoriarty** [singularity/singularity#92]
Hello!
I have made russian localization for this great game! https://github.com/DrMoriarty/singularity/commit/568dc704525a8bb69434c965757c8ce6bbc6d19e

But I have a problem. The default font `acknowtt.ttf` have no russian symbols. So I made a copy of default theme and changed special font to `Sports World-Regular.ttf` (https://www.freefontspro.com/13658/sports-world.ttf)

But when I selected my custom theme the fonts still are used from the default one.

And a couple of screenshots with this new font:
![2018-07-14 18 54 24](https://user-images.githubusercontent.com/1177068/42726102-ae075500-8797-11e8-8dfb-1eeac3404246.png)

![2018-07-14 18 54 38](https://user-images.githubusercontent.com/1177068/42726105-b6000554-8797-11e8-9c81-160f1512986e.png)

**Comment by Xenega** [comment]
You need to modify [theme.dat](../blob/master/data/themes/default/theme.dat). The ini have a section font.

Otherwise if you want your traduction added in singularity, we won't add new theme but modify the current font. However, the font you use is too different from default font. Could you find a better font?

**Comment by DrMoriarty** [comment]
@Xenega Does it means that there are no way to create one more theme with another non default font?
I would prefer do not change the default theme and simply make font replacement for additional one. Because I don't know how new font will behave itself in other localizations (may be it lacks some symbols for european languages)

**Comment by Xenega** [comment]
No you can add a theme.dat to a new theme. Just copy it or create from empty file.

**Comment by DrMoriarty** [comment]
@Xenega 
Ok. I copied theme.dat (and other theme files) from the default one to russian theme. I changed special font to Sports_World-Regular.ttf. When I started the game and changed the theme to the new one I get:
![2018-07-16 10 34 50](https://user-images.githubusercontent.com/1177068/42747213-234662f0-88e4-11e8-813e-6407587bfac2.png)
![2018-07-16 10 35 06](https://user-images.githubusercontent.com/1177068/42747220-2a401c68-88e4-11e8-934a-dd6bb996c7fc.png)
What I did wrong?

**Comment by DrMoriarty** [comment]
I already wrote (in my original bug report) that the game uses font from the default theme even if I select the theme with the redefined font.

**Comment by DrMoriarty** [comment]
The screenshots in bugreport shows the state when I changed the font in the DEFAULT theme (so you can see that localization files are valid and the problem in the using the wrong font)

**Comment by Xenega** [comment]
Seems its needs to restart to works. Too many harcoded things.

**Comment by DrMoriarty** [comment]
@Xenega Yes! Restarting the game after theme selection did the trick.
Sorry, I might have guessed before.

**Comment by Xenega** [comment]
It's a bug on my part, theme shouldn't need restart. My bad. Sorry.
